spring.application.name=server-manager
server.data.dir=D:/code/java/server-manager/data
app.api-key=3GAelYSFnAoFpEYv0oxiMvNc4k9_4gCAxuKhaXFZ5S4s1RJim

# Terraria paths
terraria.server.dir=D:/steam/steamapps/common/Terraria
terraria.worlds.dir=C:/Users/kalla/Documents/My Games/Terraria/Worlds

# tModLoader paths
tmodloader.server.dir=D:/steam/steamapps/common/tModLoader
tmodloader.worlds.dir=C:/Users/kalla/Documents/My Games/Terraria/tModLoader/Worlds
tmodloader.mods.enabled.path=C:/Users/kalla/Documents/My Games/Terraria/tModLoader/Mods/enabled.json
